//go:build !dot && !spot

package dashboard

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/HuskerMinion/techo5/echod/internal/lib/hass"
)

// A dashboard of Home Assistant's own, drawn card by card. The cards people use most become tiles,
// headings and text in the device's own style; stacks and grids are flattened into the page; a
// card the device does not know is a tile that says what it is, so nothing silently goes missing.
//
// A dashboard Home Assistant generates for itself (the default Overview, until somebody takes it
// over) has no cards to read, and is drawn as the Rooms dashboard, which is what it would show.

type lovelaceSource struct {
	dashboard string // url_path; "lovelace" for the default
	view      string // a view's path or index; empty for the first

	nodes     []node
	ids       []string
	templates []template
	fallback  *roomsSource
}

func newLovelace(path string) *lovelaceSource {
	dash, view, _ := strings.Cut(strings.Trim(path, "/"), "/")
	return &lovelaceSource{dashboard: dash, view: view}
}

func (l *lovelaceSource) load(ctx context.Context, live *hass.Live) ([]string, []template, error) {
	cmd := map[string]any{"type": "lovelace/config"}
	if l.dashboard != "" && l.dashboard != "lovelace" {
		cmd["url_path"] = l.dashboard
	}
	rawCfg, err := live.Call(ctx, cmd)
	if err != nil {
		return nil, nil, fmt.Errorf("Home Assistant would not give this dashboard.")
	}
	var cfg struct {
		Views    []raw `json:"views"`
		Strategy raw   `json:"strategy"`
	}
	if err := json.Unmarshal(rawCfg, &cfg); err != nil {
		return nil, nil, err
	}
	if len(cfg.Views) == 0 {
		// Generated by Home Assistant: its areas are what it would show.
		l.fallback = &roomsSource{}
		return l.fallback.load(ctx, live)
	}
	view := cfg.Views[0]
	for i, v := range cfg.Views {
		if str(v, "path") == l.view || strconv.Itoa(i) == l.view {
			view = v
		}
	}

	c := &compiler{seen: map[string]bool{}}
	c.badges(view["badges"])
	if sections, ok := view["sections"].([]any); ok {
		for _, s := range sections {
			if sm, ok := s.(raw); ok {
				c.cards(sm["cards"])
			}
		}
	}
	c.cards(view["cards"])
	l.nodes, l.ids, l.templates = c.nodes, c.ids, c.templates
	return l.ids, l.templates, nil
}

func (l *lovelaceSource) blocks(states map[string]hass.LiveEntity, rendered map[int]string) []Block {
	if l.fallback != nil {
		return l.fallback.blocks(states, rendered)
	}
	var out []Block
	for _, n := range l.nodes {
		out = append(out, n.blocks(states, rendered)...)
	}
	// Tiles one after another make one grid, however many cards they came from, and go under the
	// heading before them: a section of tile cards is one grid in Home Assistant too.
	var merged []Block
	for _, b := range out {
		if n := len(merged); n > 0 && b.Heading == "" && len(b.Text) == 0 && len(b.Tiles) > 0 &&
			(len(merged[n-1].Tiles) > 0 || merged[n-1].Heading != "") && len(merged[n-1].Text) == 0 {
			merged[n-1].Tiles = append(merged[n-1].Tiles, b.Tiles...)
			continue
		}
		merged = append(merged, b)
	}
	return merged
}

// node is a compiled card: what it draws, given the states and templates.
type node interface {
	blocks(states map[string]hass.LiveEntity, rendered map[int]string) []Block
}

type compiler struct {
	nodes     []node
	ids       []string
	seen      map[string]bool
	templates []template
}

func (c *compiler) follow(entity string) {
	if entity != "" && !c.seen[entity] {
		c.seen[entity] = true
		c.ids = append(c.ids, entity)
	}
}

// render registers text for Home Assistant to render if it is a template, and says how to read it.
func (c *compiler) render(text, entity string) textRef {
	if !strings.Contains(text, "{{") && !strings.Contains(text, "{%") {
		return textRef{plain: text}
	}
	id := len(c.templates) + 1
	vars := map[string]any{}
	if entity != "" {
		vars["entity"] = entity
	}
	c.templates = append(c.templates, template{id: id, text: text, vars: vars})
	return textRef{template: id}
}

// textRef is words on the page: as written, or a template's latest rendering.
type textRef struct {
	plain    string
	template int
}

func (t textRef) get(rendered map[int]string) string {
	if t.template != 0 {
		return strings.TrimSpace(rendered[t.template])
	}
	return t.plain
}

func (c *compiler) cards(v any) {
	list, _ := v.([]any)
	for _, item := range list {
		if card, ok := item.(raw); ok {
			if n := c.card(card); n != nil {
				c.nodes = append(c.nodes, n)
			}
		}
	}
}

// sub compiles cards into a node of their own, for a card that holds others.
func (c *compiler) sub(v any) node {
	saved := c.nodes
	c.nodes = nil
	c.cards(v)
	inner := c.nodes
	c.nodes = saved
	return group(inner)
}

// entityCards are the cards that are one entity each, which all become a tile.
var entityCards = map[string]bool{
	"tile": true, "button": true, "entity": true, "light": true, "thermostat": true, "humidifier": true,
	"media-control": true, "sensor": true, "gauge": true, "weather-forecast": true, "alarm-panel": true,
	"custom:mushroom-entity-card": true, "custom:mushroom-light-card": true, "custom:mushroom-climate-card": true,
	"custom:mushroom-cover-card": true, "custom:mushroom-fan-card": true, "custom:mushroom-media-player-card": true,
	"custom:mushroom-lock-card": true, "custom:mushroom-person-card": true, "custom:mushroom-alarm-control-panel-card": true,
	"custom:mushroom-select-card": true, "custom:mushroom-number-card": true, "custom:mushroom-vacuum-card": true,
	"custom:mushroom-humidifier-card": true, "custom:button-card": true, "custom:bubble-card": true,
	"custom:mini-graph-card": true, "custom:mini-media-player": true,
}

func (c *compiler) card(card raw) node {
	kind := str(card, "type")
	switch {
	case kind == "heading" || kind == "custom:mushroom-title-card":
		title := str(card, "heading")
		if title == "" {
			title = str(card, "title")
		}
		return headingNode{text: c.render(title, ""), sub: c.render(str(card, "subtitle"), "")}

	case kind == "markdown":
		return textNode{title: c.render(str(card, "title"), ""), body: c.render(str(card, "content"), "")}

	case kind == "entities" || kind == "glance" || kind == "custom:mushroom-chips-card":
		n := listNode{title: c.render(str(card, "title"), "")}
		key := "entities"
		if kind == "custom:mushroom-chips-card" {
			key = "chips"
		}
		items, _ := card[key].([]any)
		for _, it := range items {
			switch row := it.(type) {
			case string:
				c.follow(row)
				n.items = append(n.items, tileItem{entity: row})
			case raw:
				if str(row, "type") == "section" {
					n.items = append(n.items, tileItem{section: str(row, "label")})
					continue
				}
				e := str(row, "entity")
				if e == "" {
					continue
				}
				c.follow(e)
				n.items = append(n.items, c.item(row, e))
			}
		}
		return n

	case kind == "custom:mushroom-template-card":
		e := str(card, "entity")
		c.follow(e)
		return templateNode{
			primary: c.render(str(card, "primary"), e), secondary: c.render(str(card, "secondary"), e),
			icon: c.render(str(card, "icon"), e), item: c.item(card, e),
		}

	case entityCards[kind]:
		e := str(card, "entity")
		if e == "" {
			// A button that only runs something: its name, its icon, what it runs.
			if a := actionOf(card, ""); a != nil {
				return listNode{items: []tileItem{{name: str(card, "name"), icon: str(card, "icon"), action: a, fixed: true}}}
			}
			return nil
		}
		c.follow(e)
		return listNode{items: []tileItem{c.item(card, e)}}

	case kind == "grid" || kind == "vertical-stack" || kind == "horizontal-stack" ||
		kind == "custom:stack-in-card" || kind == "custom:vertical-stack-in-card" || kind == "custom:layout-card":
		inner := c.sub(card["cards"])
		if title := str(card, "title"); title != "" {
			return group{headingNode{text: c.render(title, "")}, inner}
		}
		return inner

	case kind == "conditional":
		n := condNode{child: c.sub([]any{card["card"]})}
		conds, _ := card["conditions"].([]any)
		for _, x := range conds {
			if m, ok := x.(raw); ok {
				cd := cond{entity: str(m, "entity"), state: listOf(m["state"]), not: listOf(m["state_not"])}
				if cd.entity == "" {
					continue // screen, user and the like: always true here
				}
				c.follow(cd.entity)
				n.conds = append(n.conds, cd)
			}
		}
		return n
	}
	if kind == "" {
		return nil
	}
	return listNode{items: []tileItem{{name: cardName(kind), icon: "card-outline", value: "Shown when streamed", fixed: true}}}
}

// item is an entity as a card or a row presents it: its own name and icon if it gives them, and its
// tap.
func (c *compiler) item(m raw, entity string) tileItem {
	return tileItem{entity: entity, name: str(m, "name"), icon: str(m, "icon"), action: actionOf(m, entity), fixed: false}
}

// actionOf is a card's tap as a tile's action: nil for the default, which is the tile's own.
func actionOf(m raw, entity string) *Action {
	tap, _ := m["tap_action"].(raw)
	if tap == nil {
		return nil
	}
	switch str(tap, "action") {
	case "none":
		return &Action{}
	case "toggle":
		if entity == "" {
			return &Action{}
		}
		return &Action{Entity: entity, Service: "homeassistant.toggle"}
	case "call-service", "perform-action":
		service := str(tap, "perform_action")
		if service == "" {
			service = str(tap, "service")
		}
		data, _ := tap["data"].(raw)
		if data == nil {
			data, _ = tap["service_data"].(raw)
		}
		out := map[string]any{}
		for k, v := range data {
			out[k] = v
		}
		if target, ok := tap["target"].(raw); ok {
			for k, v := range target {
				out[k] = v
			}
		}
		return &Action{Entity: entity, Service: service, Data: out}
	case "navigate":
		return &Action{View: strings.Trim(str(tap, "navigation_path"), "/")}
	}
	return nil
}

func listOf(v any) []string {
	switch x := v.(type) {
	case string:
		return []string{x}
	case []any:
		var out []string
		for _, s := range x {
			if str, ok := s.(string); ok {
				out = append(out, str)
			}
		}
		return out
	}
	return nil
}

var customPrefix = regexp.MustCompile(`^custom:`)

// cardName is a card type as a person would say it: "custom:apexcharts-card" is "Apexcharts card".
func cardName(kind string) string {
	s := strings.ReplaceAll(customPrefix.ReplaceAllString(kind, ""), "-", " ")
	if s == "" {
		return "Card"
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// ---- the compiled cards --------------------------------------------------------------------------

type group []node

func (g group) blocks(states map[string]hass.LiveEntity, rendered map[int]string) []Block {
	var out []Block
	for _, n := range g {
		out = append(out, n.blocks(states, rendered)...)
	}
	return out
}

type headingNode struct{ text, sub textRef }

func (h headingNode) blocks(_ map[string]hass.LiveEntity, rendered map[int]string) []Block {
	if t := h.text.get(rendered); t != "" {
		return []Block{{Heading: t, Right: h.sub.get(rendered)}}
	}
	return nil
}

type textNode struct{ title, body textRef }

func (t textNode) blocks(_ map[string]hass.LiveEntity, rendered map[int]string) []Block {
	var out []Block
	if title := t.title.get(rendered); title != "" {
		out = append(out, Block{Heading: title})
	}
	if body := plainText(t.body.get(rendered)); len(body) > 0 {
		out = append(out, Block{Text: body})
	}
	return out
}

// tileItem is one tile a card asks for.
type tileItem struct {
	entity, name, icon, value string
	section                   string // a heading within a list instead
	action                    *Action
	fixed                     bool // not an entity's: drawn as given
}

type listNode struct {
	title textRef
	items []tileItem
}

func (l listNode) blocks(states map[string]hass.LiveEntity, rendered map[int]string) []Block {
	var out []Block
	cur := Block{Heading: l.title.get(rendered)}
	for _, it := range l.items {
		if it.section != "" {
			if cur.Heading != "" || len(cur.Tiles) > 0 {
				out = append(out, cur)
			}
			cur = Block{Heading: it.section}
			continue
		}
		cur.Tiles = append(cur.Tiles, it.tile(states))
	}
	if cur.Heading != "" || len(cur.Tiles) > 0 {
		out = append(out, cur)
	}
	return out
}

func (it tileItem) tile(states map[string]hass.LiveEntity) Tile {
	if it.fixed {
		return Tile{Name: it.name, Icon: orIcon(it.icon, "gesture-tap"), Value: it.value, Tap: it.action}
	}
	e, ok := states[it.entity]
	if !ok {
		e = hass.LiveEntity{ID: it.entity, State: "unknown", Attrs: map[string]any{}}
	}
	name := it.name
	if name == "" {
		name, _ = e.Attrs["friendly_name"].(string)
		if name == "" {
			name = it.entity
		}
	}
	t := describe(e, name)
	if it.icon != "" {
		t.Icon = it.icon
	}
	if it.action != nil {
		t.Tap = it.action
		if t.Tap.Service == "" && t.Tap.View == "" {
			t.Tap = nil // tap_action none
		}
	}
	return t
}

func orIcon(icon, fallback string) string {
	if icon == "" {
		return fallback
	}
	return icon
}

// templateNode is a Mushroom template card: its words and icon are templates.
type templateNode struct {
	primary, secondary, icon textRef
	item                     tileItem
}

func (t templateNode) blocks(states map[string]hass.LiveEntity, rendered map[int]string) []Block {
	tile := Tile{Name: t.primary.get(rendered), Value: t.secondary.get(rendered), Icon: orIcon(t.icon.get(rendered), "card-text-outline")}
	if t.item.entity != "" {
		base := t.item.tile(states)
		tile.On, tile.Gone, tile.Tap = base.On, false, base.Tap
	} else if t.item.action != nil && (t.item.action.Service != "" || t.item.action.View != "") {
		tile.Tap = t.item.action
	}
	if tile.Name == "" && tile.Value == "" {
		return nil
	}
	return []Block{{Tiles: []Tile{tile}}}
}

type cond struct {
	entity     string
	state, not []string
}

type condNode struct {
	conds []cond
	child node
}

func (c condNode) blocks(states map[string]hass.LiveEntity, rendered map[int]string) []Block {
	for _, cd := range c.conds {
		s := states[cd.entity].State
		if len(cd.state) > 0 && !contains(cd.state, s) {
			return nil
		}
		if contains(cd.not, s) {
			return nil
		}
	}
	return c.child.blocks(states, rendered)
}

func contains(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

// badges are the chips at the top of a view: a row of tiles here.
func (c *compiler) badges(v any) {
	list, _ := v.([]any)
	n := listNode{}
	for _, b := range list {
		switch x := b.(type) {
		case string:
			c.follow(x)
			n.items = append(n.items, tileItem{entity: x})
		case raw:
			if e := str(x, "entity"); e != "" {
				c.follow(e)
				n.items = append(n.items, c.item(x, e))
			}
		}
	}
	if len(n.items) > 0 {
		c.nodes = append(c.nodes, n)
	}
}

var (
	mdLink   = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)
	mdMarks  = regexp.MustCompile(`(\*\*|__|\*|_|~~|` + "`" + `)`)
	mdTags   = regexp.MustCompile(`<[^>]+>`)
	mdPrefix = regexp.MustCompile(`^\s*(#{1,6}\s+|[-*+]\s+|>\s*)`)
)

// plainText is markdown as plain paragraphs: headings, emphasis, links and tags reduced to their
// words, since the page draws text, not HTML.
func plainText(md string) []string {
	var out []string
	for _, line := range strings.Split(md, "\n") {
		line = mdPrefix.ReplaceAllString(line, "")
		line = mdLink.ReplaceAllString(line, "$1")
		line = mdTags.ReplaceAllString(line, "")
		line = mdMarks.ReplaceAllString(line, "")
		line = strings.TrimSpace(line)
		if line != "" {
			out = append(out, line)
		}
	}
	return out
}
