package home

// neighbors are the states (and D.C., Puerto Rico, the Virgin Islands) that share a border with each, so
// the rain map's alerts include those just over it: a storm does not stop at a state line.
var neighbors = map[string][]string{
	"AK": {},
	"AL": {"FL", "GA", "MS", "TN"},
	"AR": {"LA", "MO", "MS", "OK", "TN", "TX"},
	"AZ": {"CA", "CO", "NM", "NV", "UT"},
	"CA": {"AZ", "NV", "OR"},
	"CO": {"AZ", "KS", "NE", "NM", "OK", "UT", "WY"},
	"CT": {"MA", "NY", "RI"},
	"DC": {"MD", "VA"},
	"DE": {"MD", "NJ", "PA"},
	"FL": {"AL", "GA"},
	"GA": {"AL", "FL", "NC", "SC", "TN"},
	"HI": {},
	"IA": {"IL", "MN", "MO", "NE", "SD", "WI"},
	"ID": {"MT", "NV", "OR", "UT", "WA", "WY"},
	"IL": {"IN", "IA", "KY", "MO", "WI"},
	"IN": {"IL", "KY", "MI", "OH"},
	"KS": {"CO", "MO", "NE", "OK"},
	"KY": {"IL", "IN", "MO", "OH", "TN", "VA", "WV"},
	"LA": {"AR", "MS", "TX"},
	"MA": {"CT", "NH", "NY", "RI", "VT"},
	"MD": {"DE", "PA", "VA", "WV", "DC"},
	"ME": {"NH"},
	"MI": {"IN", "OH", "WI"},
	"MN": {"IA", "ND", "SD", "WI"},
	"MO": {"AR", "IL", "IA", "KS", "KY", "NE", "OK", "TN"},
	"MS": {"AL", "AR", "LA", "TN"},
	"MT": {"ID", "ND", "SD", "WY"},
	"NC": {"GA", "SC", "TN", "VA"},
	"ND": {"MN", "MT", "SD"},
	"NE": {"CO", "IA", "KS", "MO", "SD", "WY"},
	"NH": {"ME", "MA", "VT"},
	"NJ": {"DE", "NY", "PA"},
	"NM": {"AZ", "CO", "OK", "TX", "UT"},
	"NV": {"AZ", "CA", "ID", "OR", "UT"},
	"NY": {"CT", "MA", "NJ", "PA", "VT"},
	"OH": {"IN", "KY", "MI", "PA", "WV"},
	"OK": {"AR", "CO", "KS", "MO", "NM", "TX"},
	"OR": {"CA", "ID", "NV", "WA"},
	"PA": {"DE", "MD", "NJ", "NY", "OH", "WV"},
	"PR": {"VI"},
	"RI": {"CT", "MA"},
	"SC": {"GA", "NC"},
	"SD": {"IA", "MN", "MT", "NE", "ND", "WY"},
	"TN": {"AL", "AR", "GA", "KY", "MS", "MO", "NC", "VA"},
	"TX": {"AR", "LA", "NM", "OK"},
	"UT": {"AZ", "CO", "ID", "NV", "NM", "WY"},
	"VA": {"KY", "MD", "NC", "TN", "WV", "DC"},
	"VI": {"PR"},
	"VT": {"MA", "NH", "NY"},
	"WA": {"ID", "OR"},
	"WI": {"IL", "IA", "MI", "MN"},
	"WV": {"KY", "MD", "OH", "PA", "VA"},
	"WY": {"CO", "ID", "MT", "NE", "SD", "UT"},
}
