// Command mkmanifest writes the manifest a device fetches to learn a release exists.
//
// It lives here rather than in the release workflow so that the file CI publishes and the struct echod
// parses are the same definition. A manifest generated by a shell script would be free to drift from
// what the device expects, and the failure would only show up as a device that will not update.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/HuskerMinion/techo5/echod/internal/update"
)

func main() {
	var (
		m update.Manifest

		from   = flag.String("from", "", "where this release's assets can be fetched from")
		arm64  = flag.String("arm64", "", "the arm64 build, hashed and measured")
		arm    = flag.String("arm", "", "the arm build, hashed and measured")
		rootfs = flag.String("rootfs-arm", "", "the arm rootfs tarball for slot devices, hashed and measured")
		// The Echo Dot 2 shares the Show's architecture but not its hardware, so its builds are keyed
		// apart ("arm-dot", see internal/update/arch_dot.go) and a device only ever sees its own.
		armDot    = flag.String("arm-dot", "", "the Echo Dot build (-tags dot), hashed and measured")
		rootfsDot = flag.String("rootfs-arm-dot", "", "the Echo Dot rootfs tarball, hashed and measured")
		// The Echo Spot likewise ("arm-spot", internal/update/arch_spot.go).
		armSpot    = flag.String("arm-spot", "", "the Echo Spot build (-tags spot), hashed and measured")
		rootfsSpot = flag.String("rootfs-arm-spot", "", "the Echo Spot rootfs tarball, hashed and measured")
		out        = flag.String("out", "", "where to write the manifest, or stdout")
		// Devices believe a manifest only with the release key's signature beside it
		// (internal/update/trust.go), so a release without one offers nothing.
		signKey = flag.String("sign-key", "", "the release signing key file; writes <out>.sig next to the manifest")
	)
	flag.StringVar(&m.Version, "version", "", "version as Home Assistant will compare it")
	flag.StringVar(&m.Title, "title", "", "title for Home Assistant's update card")
	flag.StringVar(&m.Notes, "notes", "", "release notes, shown on the card")
	flag.StringVar(&m.ReleaseURL, "release-url", "", "what the card's link points at")
	flag.Parse()

	builds := map[string]string{"arm64": *arm64, "arm": *arm, "arm-dot": *armDot, "arm-spot": *armSpot}
	rootfses := map[string]string{"arm": *rootfs, "arm-dot": *rootfsDot, "arm-spot": *rootfsSpot}
	if err := run(m, *from, builds, rootfses, *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if *signKey != "" {
		if err := sign(*out, *signKey); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}

// sign writes the detached signature over the manifest exactly as written.
func sign(out, keyFile string) error {
	if out == "" {
		return fmt.Errorf("mkmanifest: -sign-key needs -out")
	}
	manifest, err := os.ReadFile(out)
	if err != nil {
		return err
	}
	seed, err := os.ReadFile(keyFile)
	if err != nil {
		return err
	}
	sig, err := update.Sign(manifest, string(seed))
	if err != nil {
		return err
	}
	return os.WriteFile(out+".sig", []byte(sig), 0o644)
}

// tagName is the mistake this guard exists for. A device's tag says which device the build is for
// (dot-vX.Y.Z, spot-vX.Y.Z; see .github/workflows/build.yml), and the binary built from it is stamped
// with the version alone. Handing the tag to -version publishes a manifest saying dot-v0.5.10 beside
// binaries that report v0.5.10, and Home Assistant offers an update whenever the two strings differ —
// so every Dot and Spot in the field ends up with a card it can never clear.
var tagName = regexp.MustCompile(`^(dot|spot)-v`)

// checkVersion refuses a version before anything is measured or written, so a bad one costs a line of
// output rather than a published release.
//
// A tag's prefix is refused rather than stripped. Stripping it would be the easier fix, but silently
// accepting a tag is how this shipped in the first place: the release would go out looking correct,
// and nothing would tell whoever ran it that the two names had drifted apart. Refusing puts the
// correction where the tag and the version are both in front of somebody.
func checkVersion(version string) error {
	if tagName.MatchString(version) {
		_, v, _ := strings.Cut(version, "-")
		return fmt.Errorf("mkmanifest: -version %s is a tag name, not a version; the binaries this release ships are stamped %s, so pass -version %s", version, v, v)
	}
	return update.ValidVersion(version)
}

func run(m update.Manifest, from string, builds map[string]string, rootfses map[string]string, out string) error {
	if m.Version == "" || from == "" || (builds["arm64"] == "" && builds["arm"] == "" && builds["arm-dot"] == "" && builds["arm-spot"] == "") {
		return fmt.Errorf("mkmanifest: -version, -from and at least one of -arm64/-arm/-arm-dot/-arm-spot are required")
	}
	if err := checkVersion(m.Version); err != nil {
		return err
	}

	m.Binaries = make(map[string]update.Binary, len(builds))
	for arch, path := range builds {
		if path == "" {
			continue
		}
		b, err := measure(path)
		if err != nil {
			return err
		}
		b.URL = from + "/" + filepath.Base(path)
		m.Binaries[arch] = b
	}

	// The flat fields are what an older device reads; they carry the arm64 build where there is one,
	// and the arm build for a release that only has that (TECHO5 on cronos is 32-bit).
	for arch, path := range rootfses {
		if path == "" {
			continue
		}
		b, err := measure(path)
		if err != nil {
			return err
		}
		b.URL = from + "/" + filepath.Base(path)
		if m.Rootfs == nil {
			m.Rootfs = make(map[string]update.Binary)
		}
		m.Rootfs[arch] = b
	}
	flat, ok := m.Binaries["arm64"]
	if !ok {
		flat = m.Binaries["arm"]
	}
	m.URL, m.SHA256, m.Size = flat.URL, flat.SHA256, flat.Size

	// The same rules the device applies, so a release cannot publish a manifest every device will reject.
	if err := m.Valid(); err != nil {
		return err
	}

	encoded, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	encoded = append(encoded, '\n')

	if out == "" {
		_, err = os.Stdout.Write(encoded)
		return err
	}
	return os.WriteFile(out, encoded, 0o644)
}

// measure is what a device checks its download against, taken from the file the release will upload.
func measure(path string) (update.Binary, error) {
	f, err := os.Open(path)
	if err != nil {
		return update.Binary{}, err
	}
	defer f.Close()

	sum := sha256.New()
	size, err := io.Copy(sum, f)
	if err != nil {
		return update.Binary{}, err
	}
	return update.Binary{SHA256: hex.EncodeToString(sum.Sum(nil)), Size: size}, nil
}
